//! # Solidity Verifier Contract Generation
#![allow(missing_docs)]
//!
//! Generates a Solidity smart contract that verifies UniGroth/Groth16 proofs
//! on-chain. Uses BN254 precompiles (EIP-196/197).
//!
//! References:
//! - EIP-196: <https://eips.ethereum.org/EIPS/eip-196>
//! - EIP-197: <https://eips.ethereum.org/EIPS/eip-197>

use ark_bn254::{Bn254, G1Affine, G2Affine};
use ark_ec::AffineRepr;
use ark_serialize::CanonicalSerialize;
use ark_std::{format, string::String, vec::Vec};

use crate::VerifyingKey;

/// Gas cost estimates for on-chain verification.
#[derive(Clone, Debug)]
pub struct GasCostEstimate {
    pub ec_add_calls: usize,
    pub ec_mul_calls: usize,
    pub pairing_calls: usize,
    pub total_gas: usize,
}

/// Estimate gas cost for verifying a proof with the given number of public inputs.
pub fn estimate_gas_cost(num_public_inputs: usize) -> GasCostEstimate {
    let ec_add_calls = num_public_inputs;
    let ec_mul_calls = num_public_inputs;
    let pairing_calls = 1;

    let ec_add_gas = 150 * ec_add_calls;
    let ec_mul_gas = 6000 * ec_mul_calls;
    let pairing_gas = 45000 + 34000 * 4;
    let calldata_gas = 16 * (256 + 32 * num_public_inputs);
    let overhead = 25000;

    GasCostEstimate {
        ec_add_calls,
        ec_mul_calls,
        pairing_calls,
        total_gas: ec_add_gas + ec_mul_gas + pairing_gas + calldata_gas + overhead,
    }
}

fn serialize_point_hex(point_bytes: &[u8]) -> String {
    let hex: String = point_bytes
        .iter()
        .rev()
        .map(|b| format!("{:02x}", b))
        .collect();
    format!("0x{}", hex)
}

fn format_g1(p: &G1Affine) -> (String, String) {
    if p.is_zero() {
        return ("0".into(), "0".into());
    }
    let mut buf = Vec::new();
    p.serialize_uncompressed(&mut buf).unwrap();
    // G1 uncompressed = x (32 bytes) || y (32 bytes), little-endian
    let x_hex = serialize_point_hex(&buf[..32]);
    let y_hex = serialize_point_hex(&buf[32..64]);
    (x_hex, y_hex)
}

fn format_g2(p: &G2Affine) -> ((String, String), (String, String)) {
    if p.is_zero() {
        return (("0".into(), "0".into()), ("0".into(), "0".into()));
    }
    let mut buf = Vec::new();
    p.serialize_uncompressed(&mut buf).unwrap();
    // G2 uncompressed = x.c0 (32) || x.c1 (32) || y.c0 (32) || y.c1 (32)
    let x_c0 = serialize_point_hex(&buf[0..32]);
    let x_c1 = serialize_point_hex(&buf[32..64]);
    let y_c0 = serialize_point_hex(&buf[64..96]);
    let y_c1 = serialize_point_hex(&buf[96..128]);
    // Solidity expects [c1, c0] (imaginary first)
    ((x_c1, x_c0), (y_c1, y_c0))
}

/// Generate a Solidity verifier contract for the given verifying key.
pub fn generate_solidity_verifier(vk: &VerifyingKey<Bn254>, contract_name: &str) -> String {
    let num_inputs = vk.gamma_abc_g1.len() - 1;

    let (alpha_x, alpha_y) = format_g1(&vk.alpha_g1);
    let ((beta_x1, beta_x0), (beta_y1, beta_y0)) = format_g2(&vk.beta_g2);
    let ((gamma_x1, gamma_x0), (gamma_y1, gamma_y0)) = format_g2(&vk.gamma_g2);
    let ((delta_x1, delta_x0), (delta_y1, delta_y0)) = format_g2(&vk.delta_g2);

    let mut ic_entries = String::new();
    for (i, point) in vk.gamma_abc_g1.iter().enumerate() {
        let (x, y) = format_g1(point);
        ic_entries.push_str(&format!(
            "        vk.IC[{}] = Pairing.G1Point({}, {});\n",
            i, x, y
        ));
    }

    format!(
        r#"// SPDX-License-Identifier: MIT
// Auto-generated by UniGroth Solidity Verifier Generator
pragma solidity ^0.8.0;

library Pairing {{
    struct G1Point {{
        uint256 X;
        uint256 Y;
    }}
    struct G2Point {{
        uint256[2] X;
        uint256[2] Y;
    }}

    function negate(G1Point memory p) internal pure returns (G1Point memory) {{
        uint256 q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;
        if (p.X == 0 && p.Y == 0) return G1Point(0, 0);
        return G1Point(p.X, q - (p.Y % q));
    }}

    function addition(G1Point memory p1, G1Point memory p2) internal view returns (G1Point memory r) {{
        uint256[4] memory input;
        input[0] = p1.X; input[1] = p1.Y;
        input[2] = p2.X; input[3] = p2.Y;
        bool success;
        assembly {{ success := staticcall(sub(gas(), 2000), 6, input, 0xc0, r, 0x60) }}
        require(success, "ec-add-failed");
    }}

    function scalar_mul(G1Point memory p, uint256 s) internal view returns (G1Point memory r) {{
        uint256[3] memory input;
        input[0] = p.X; input[1] = p.Y; input[2] = s;
        bool success;
        assembly {{ success := staticcall(sub(gas(), 2000), 7, input, 0x60, r, 0x40) }}
        require(success, "ec-mul-failed");
    }}

    function pairingProd4(
        G1Point memory a1, G2Point memory a2,
        G1Point memory b1, G2Point memory b2,
        G1Point memory c1, G2Point memory c2,
        G1Point memory d1, G2Point memory d2
    ) internal view returns (bool) {{
        uint256[24] memory input;
        input[0] = a1.X; input[1] = a1.Y;
        input[2] = a2.X[0]; input[3] = a2.X[1]; input[4] = a2.Y[0]; input[5] = a2.Y[1];
        input[6] = b1.X; input[7] = b1.Y;
        input[8] = b2.X[0]; input[9] = b2.X[1]; input[10] = b2.Y[0]; input[11] = b2.Y[1];
        input[12] = c1.X; input[13] = c1.Y;
        input[14] = c2.X[0]; input[15] = c2.X[1]; input[16] = c2.Y[0]; input[17] = c2.Y[1];
        input[18] = d1.X; input[19] = d1.Y;
        input[20] = d2.X[0]; input[21] = d2.X[1]; input[22] = d2.Y[0]; input[23] = d2.Y[1];
        uint256[1] memory out;
        bool success;
        assembly {{ success := staticcall(sub(gas(), 2000), 8, input, 0x300, out, 0x20) }}
        require(success, "pairing-failed");
        return out[0] != 0;
    }}
}}

contract {contract_name} {{
    using Pairing for *;

    struct VerifyingKey {{
        Pairing.G1Point alpha_g1;
        Pairing.G2Point beta_g2;
        Pairing.G2Point gamma_g2;
        Pairing.G2Point delta_g2;
        Pairing.G1Point[] IC;
    }}

    struct Proof {{
        Pairing.G1Point A;
        Pairing.G2Point B;
        Pairing.G1Point C;
    }}

    function verifyingKey() internal pure returns (VerifyingKey memory vk) {{
        vk.alpha_g1 = Pairing.G1Point({alpha_x}, {alpha_y});
        vk.beta_g2 = Pairing.G2Point([{beta_x1}, {beta_x0}], [{beta_y1}, {beta_y0}]);
        vk.gamma_g2 = Pairing.G2Point([{gamma_x1}, {gamma_x0}], [{gamma_y1}, {gamma_y0}]);
        vk.delta_g2 = Pairing.G2Point([{delta_x1}, {delta_x0}], [{delta_y1}, {delta_y0}]);
        vk.IC = new Pairing.G1Point[]({num_ic});
{ic_entries}    }}

    function verify(uint256[] memory input, Proof memory proof) public view returns (bool) {{
        uint256 snark_scalar_field = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
        VerifyingKey memory vk = verifyingKey();
        require(input.length + 1 == vk.IC.length, "verifier-bad-input");

        Pairing.G1Point memory vk_x = Pairing.G1Point(0, 0);
        vk_x = Pairing.addition(vk_x, vk.IC[0]);
        for (uint256 i = 0; i < input.length; i++) {{
            require(input[i] < snark_scalar_field, "verifier-gte-snark-scalar-field");
            vk_x = Pairing.addition(vk_x, Pairing.scalar_mul(vk.IC[i + 1], input[i]));
        }}

        return Pairing.pairingProd4(
            Pairing.negate(proof.A), proof.B,
            vk.alpha_g1, vk.beta_g2,
            vk_x, vk.gamma_g2,
            proof.C, vk.delta_g2
        );
    }}

    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[{num_inputs}] memory input
    ) public view returns (bool r) {{
        Proof memory proof;
        proof.A = Pairing.G1Point(a[0], a[1]);
        proof.B = Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]);
        proof.C = Pairing.G1Point(c[0], c[1]);
        uint256[] memory inputValues = new uint256[]({num_inputs});
        for (uint256 i = 0; i < {num_inputs}; i++) {{
            inputValues[i] = input[i];
        }}
        return verify(inputValues, proof);
    }}
}}"#,
        contract_name = contract_name,
        alpha_x = alpha_x,
        alpha_y = alpha_y,
        beta_x1 = beta_x1,
        beta_x0 = beta_x0,
        beta_y1 = beta_y1,
        beta_y0 = beta_y0,
        gamma_x1 = gamma_x1,
        gamma_x0 = gamma_x0,
        gamma_y1 = gamma_y1,
        gamma_y0 = gamma_y0,
        delta_x1 = delta_x1,
        delta_x0 = delta_x0,
        delta_y1 = delta_y1,
        delta_y0 = delta_y0,
        num_ic = vk.gamma_abc_g1.len(),
        ic_entries = ic_entries,
        num_inputs = num_inputs,
    )
}

/// Compare gas costs across proof systems.
pub fn gas_cost_comparison(num_public_inputs: usize) -> Vec<(&'static str, GasCostEstimate)> {
    let unigroth = estimate_gas_cost(num_public_inputs);

    let plonk = GasCostEstimate {
        ec_add_calls: 20 + num_public_inputs,
        ec_mul_calls: 15 + num_public_inputs,
        pairing_calls: 1,
        total_gas: 300_000 + num_public_inputs * 6000,
    };

    let stark = GasCostEstimate {
        ec_add_calls: 0,
        ec_mul_calls: 0,
        pairing_calls: 0,
        total_gas: 2_000_000 + num_public_inputs * 1000,
    };

    vec![
        ("UniGroth/Groth16", unigroth),
        ("Plonk (estimated)", plonk),
        ("STARK (estimated)", stark),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Groth16;
    use ark_bn254::{Bn254, Fr};
    use ark_crypto_primitives::snark::SNARK;
    use ark_relations::{
        gr1cs::{ConstraintSynthesizer, ConstraintSystemRef, SynthesisError},
        lc,
    };
    use ark_std::rand::{RngCore, SeedableRng};

    fn make_rng() -> ark_std::rand::rngs::StdRng {
        ark_std::rand::rngs::StdRng::seed_from_u64(ark_std::test_rng().next_u64())
    }

    #[derive(Clone)]
    struct MulCircuit {
        a: Option<Fr>,
        b: Option<Fr>,
    }

    impl ConstraintSynthesizer<Fr> for MulCircuit {
        fn generate_constraints(self, cs: ConstraintSystemRef<Fr>) -> Result<(), SynthesisError> {
            let a = cs.new_witness_variable(|| self.a.ok_or(SynthesisError::AssignmentMissing))?;
            let b = cs.new_witness_variable(|| self.b.ok_or(SynthesisError::AssignmentMissing))?;
            let c_val = self.a.unwrap_or_default() * self.b.unwrap_or_default();
            let c = cs.new_input_variable(|| Ok(c_val))?;
            cs.enforce_r1cs_constraint(|| lc!() + a, || lc!() + b, || lc!() + c)?;
            Ok(())
        }
    }

    #[test]
    fn test_solidity_generation() {
        let mut rng = make_rng();
        let (_, vk) =
            Groth16::<Bn254>::circuit_specific_setup(MulCircuit { a: None, b: None }, &mut rng)
                .unwrap();

        let sol = generate_solidity_verifier(&vk, "UniGrothVerifier");
        assert!(sol.contains("contract UniGrothVerifier"));
        assert!(sol.contains("function verify("));
        assert!(sol.contains("function verifyProof("));
        assert!(sol.contains("pairingProd4"));
        assert!(sol.contains("SPDX-License-Identifier"));
    }

    #[test]
    fn test_gas_estimate() {
        let est = estimate_gas_cost(2);
        assert!(est.total_gas > 0);
        assert_eq!(est.pairing_calls, 1);
        assert_eq!(est.ec_mul_calls, 2);
    }

    #[test]
    fn test_gas_comparison() {
        let comparison = gas_cost_comparison(2);
        assert_eq!(comparison.len(), 3);
        let groth16_gas = comparison[0].1.total_gas;
        let plonk_gas = comparison[1].1.total_gas;
        let stark_gas = comparison[2].1.total_gas;
        assert!(groth16_gas < plonk_gas);
        assert!(plonk_gas < stark_gas);
    }
}
