//! # WASM Verifier Code Generation
#![allow(missing_docs)]
//!
//! Generates a standalone Rust source file that compiles to WebAssembly for
//! verifying UniGroth/Groth16 proofs in the browser or any WASM runtime.
//!
//! The generated code is self-contained: it embeds the verifying key constants
//! and exposes a `verify_proof(proof_bytes, public_inputs_bytes) -> bool` entry
//! point via `wasm-bindgen`.
//!
//! ## Usage
//! ```rust,ignore
//! let wasm_src = generate_wasm_verifier(&vk, "my_circuit");
//! std::fs::write("verifier/src/lib.rs", wasm_src).unwrap();
//! // Then: cd verifier && wasm-pack build --target web
//! ```

use ark_bn254::{Bn254, G1Affine, G2Affine};
use ark_ec::AffineRepr;
use ark_serialize::CanonicalSerialize;
use ark_std::{format, string::String, vec::Vec};

use crate::VerifyingKey;

/// Serialize a G1 affine point to compressed hex bytes.
fn g1_compressed_hex(p: &G1Affine) -> String {
    if p.is_zero() {
        return "vec![0u8; 32]".into();
    }
    let mut buf = Vec::new();
    p.serialize_compressed(&mut buf).unwrap();
    let hex: String = buf.iter().map(|b| format!("0x{:02x},", b)).collect();
    format!("vec![{}]", hex)
}

/// Serialize a G2 affine point to compressed hex bytes.
fn g2_compressed_hex(p: &G2Affine) -> String {
    if p.is_zero() {
        return "vec![0u8; 64]".into();
    }
    let mut buf = Vec::new();
    p.serialize_compressed(&mut buf).unwrap();
    let hex: String = buf.iter().map(|b| format!("0x{:02x},", b)).collect();
    format!("vec![{}]", hex)
}

/// Estimate the WASM binary size for a verifier with the given number of public inputs.
pub fn estimate_wasm_size(num_public_inputs: usize) -> WasmSizeEstimate {
    // Base WASM (arkworks pairing + BN254): ~800KB stripped
    let base_wasm_kb = 800;
    // Each IC point adds ~32 bytes compressed
    let vk_overhead_kb = (num_public_inputs + 1) * 32 / 1024;
    WasmSizeEstimate {
        base_wasm_kb,
        vk_overhead_kb,
        total_estimate_kb: base_wasm_kb + vk_overhead_kb,
        num_public_inputs,
    }
}

/// Estimated WASM binary size.
#[derive(Clone, Debug)]
pub struct WasmSizeEstimate {
    /// Base WASM size (pairing library + BN254)
    pub base_wasm_kb: usize,
    /// Additional size from embedded VK
    pub vk_overhead_kb: usize,
    /// Total estimated WASM binary size
    pub total_estimate_kb: usize,
    /// Number of public inputs
    pub num_public_inputs: usize,
}

/// Generate a Rust source file for a WASM verifier.
///
/// The output is a complete `lib.rs` that can be compiled with `wasm-pack`.
/// It embeds the verifying key and exposes `verify_proof()` via wasm-bindgen.
pub fn generate_wasm_verifier(vk: &VerifyingKey<Bn254>, circuit_name: &str) -> String {
    let num_inputs = vk.gamma_abc_g1.len() - 1;

    let alpha_g1_bytes = g1_compressed_hex(&vk.alpha_g1);
    let beta_g2_bytes = g2_compressed_hex(&vk.beta_g2);
    let gamma_g2_bytes = g2_compressed_hex(&vk.gamma_g2);
    let delta_g2_bytes = g2_compressed_hex(&vk.delta_g2);

    let mut ic_entries = String::new();
    for (i, point) in vk.gamma_abc_g1.iter().enumerate() {
        let bytes = g1_compressed_hex(point);
        ic_entries.push_str(&format!("        ic_bytes.push({});\n", bytes));
        let _ = i; // suppress warning
    }

    format!(
        r#"//! Auto-generated WASM verifier for circuit: {circuit_name}
//! Generated by UniGroth WASM Verifier Generator
//!
//! Build: wasm-pack build --target web
//! Usage: import init, {{ verify_proof }} from './pkg/verifier.js';

use ark_bn254::{{Bn254, Fr, G1Affine, G2Affine}};
use ark_ec::{{pairing::Pairing, AffineRepr, CurveGroup}};
use ark_ff::PrimeField;
use ark_serialize::CanonicalDeserialize;
use wasm_bindgen::prelude::*;

const NUM_PUBLIC_INPUTS: usize = {num_inputs};

/// Deserialize the embedded verifying key.
fn load_vk() -> (G1Affine, G2Affine, G2Affine, G2Affine, Vec<G1Affine>) {{
    let alpha_g1 = G1Affine::deserialize_compressed({alpha_g1_bytes}.as_slice()).unwrap();
    let beta_g2 = G2Affine::deserialize_compressed({beta_g2_bytes}.as_slice()).unwrap();
    let gamma_g2 = G2Affine::deserialize_compressed({gamma_g2_bytes}.as_slice()).unwrap();
    let delta_g2 = G2Affine::deserialize_compressed({delta_g2_bytes}.as_slice()).unwrap();

    let mut ic_bytes: Vec<Vec<u8>> = Vec::new();
{ic_entries}
    let ic: Vec<G1Affine> = ic_bytes.iter()
        .map(|b| G1Affine::deserialize_compressed(b.as_slice()).unwrap())
        .collect();

    (alpha_g1, beta_g2, gamma_g2, delta_g2, ic)
}}

/// Verify a Groth16 proof.
///
/// # Arguments
/// * `proof_a` - Compressed G1 point (A element)
/// * `proof_b` - Compressed G2 point (B element)
/// * `proof_c` - Compressed G1 point (C element)
/// * `public_inputs` - Serialized field elements (32 bytes each, little-endian)
///
/// # Returns
/// `true` if the proof is valid, `false` otherwise.
#[wasm_bindgen]
pub fn verify_proof(
    proof_a: &[u8],
    proof_b: &[u8],
    proof_c: &[u8],
    public_inputs: &[u8],
) -> bool {{
    let a = match G1Affine::deserialize_compressed(proof_a) {{
        Ok(p) => p,
        Err(_) => return false,
    }};
    let b = match G2Affine::deserialize_compressed(proof_b) {{
        Ok(p) => p,
        Err(_) => return false,
    }};
    let c = match G1Affine::deserialize_compressed(proof_c) {{
        Ok(p) => p,
        Err(_) => return false,
    }};

    // Parse public inputs (32 bytes each, little-endian)
    if public_inputs.len() != NUM_PUBLIC_INPUTS * 32 {{
        return false;
    }}
    let inputs: Vec<Fr> = (0..NUM_PUBLIC_INPUTS)
        .map(|i| Fr::from_le_bytes_mod_order(&public_inputs[i*32..(i+1)*32]))
        .collect();

    let (alpha_g1, beta_g2, gamma_g2, delta_g2, ic) = load_vk();

    // Compute linear combination of public inputs
    let mut acc = ic[0].into_group();
    for (inp, base) in inputs.iter().zip(ic[1..].iter()) {{
        acc += base.mul_bigint(inp.into_bigint());
    }}
    let vk_x = acc.into_affine();

    // Pairing check: e(A,B) · e(vk_x, -gamma) · e(C, -delta) = e(alpha, beta)
    use core::ops::Neg;
    let neg_gamma = gamma_g2.into_group().neg().into_affine();
    let neg_delta = delta_g2.into_group().neg().into_affine();

    let ml = Bn254::multi_miller_loop(
        [a.into(), vk_x.into(), c.into()],
        [b.into(), neg_gamma.into(), neg_delta.into()],
    );
    let result = Bn254::final_exponentiation(ml).unwrap();

    let target = Bn254::pairing(alpha_g1, beta_g2);
    result == target
}}

/// Get the number of public inputs expected by this verifier.
#[wasm_bindgen]
pub fn num_public_inputs() -> usize {{
    NUM_PUBLIC_INPUTS
}}

/// Get the circuit name.
#[wasm_bindgen]
pub fn circuit_name() -> String {{
    "{circuit_name}".to_string()
}}
"#,
        circuit_name = circuit_name,
        num_inputs = num_inputs,
        alpha_g1_bytes = alpha_g1_bytes,
        beta_g2_bytes = beta_g2_bytes,
        gamma_g2_bytes = gamma_g2_bytes,
        delta_g2_bytes = delta_g2_bytes,
        ic_entries = ic_entries,
    )
}

/// Generate a Cargo.toml for the WASM verifier project.
pub fn generate_wasm_cargo_toml(circuit_name: &str) -> String {
    format!(
        r#"[package]
name = "{circuit_name}-verifier"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ark-bn254 = {{ git = "https://github.com/arkworks-rs/algebra.git", default-features = false, features = ["curve"] }}
ark-ec = {{ git = "https://github.com/arkworks-rs/algebra.git", default-features = false }}
ark-ff = {{ git = "https://github.com/arkworks-rs/algebra.git", default-features = false }}
ark-serialize = {{ git = "https://github.com/arkworks-rs/algebra.git", default-features = false }}
ark-std = {{ version = "0.5.0", default-features = false }}
wasm-bindgen = "0.2"

[profile.release]
opt-level = "z"
lto = true
"#,
        circuit_name = circuit_name,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Groth16;
    use ark_bn254::{Bn254, Fr};
    use ark_crypto_primitives::snark::SNARK;
    use ark_relations::{
        gr1cs::{ConstraintSynthesizer, ConstraintSystemRef, SynthesisError},
        lc,
    };
    use ark_std::rand::{RngCore, SeedableRng};

    fn make_rng() -> ark_std::rand::rngs::StdRng {
        ark_std::rand::rngs::StdRng::seed_from_u64(ark_std::test_rng().next_u64())
    }

    #[derive(Clone)]
    struct MulCircuit {
        a: Option<Fr>,
        b: Option<Fr>,
    }

    impl ConstraintSynthesizer<Fr> for MulCircuit {
        fn generate_constraints(self, cs: ConstraintSystemRef<Fr>) -> Result<(), SynthesisError> {
            let a = cs.new_witness_variable(|| self.a.ok_or(SynthesisError::AssignmentMissing))?;
            let b = cs.new_witness_variable(|| self.b.ok_or(SynthesisError::AssignmentMissing))?;
            let c_val = self.a.unwrap_or_default() * self.b.unwrap_or_default();
            let c = cs.new_input_variable(|| Ok(c_val))?;
            cs.enforce_r1cs_constraint(|| lc!() + a, || lc!() + b, || lc!() + c)?;
            Ok(())
        }
    }

    #[test]
    fn test_wasm_generation() {
        let mut rng = make_rng();
        let (_, vk) =
            Groth16::<Bn254>::circuit_specific_setup(MulCircuit { a: None, b: None }, &mut rng)
                .unwrap();

        let src = generate_wasm_verifier(&vk, "test_mul");
        assert!(src.contains("verify_proof"));
        assert!(src.contains("wasm_bindgen"));
        assert!(src.contains("NUM_PUBLIC_INPUTS: usize = 1"));
        assert!(src.contains("deserialize_compressed"));
        assert!(src.contains("multi_miller_loop"));
    }

    #[test]
    fn test_wasm_cargo_toml() {
        let toml = generate_wasm_cargo_toml("my_circuit");
        assert!(toml.contains("my_circuit-verifier"));
        assert!(toml.contains("wasm-bindgen"));
        assert!(toml.contains("ark-bn254"));
    }

    #[test]
    fn test_wasm_size_estimate() {
        let est = estimate_wasm_size(5);
        assert!(est.total_estimate_kb > 0);
        assert_eq!(est.num_public_inputs, 5);
    }
}
